// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvonbygdjmjvwvdtgpjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2b25ieWdkam1qdnd2ZHRncGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDQxNzMsImV4cCI6MjA1ODA4MDE3M30.ubfR1ycJnpdf-IaL6jtj1y5AmucAIUkaoB7k6AlGosc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);